config/routes.rb
Rails.application.routes.draw do
  root 'shorturls#new'
  resources :shorturls
  get 's/:short_url' => 'shorturls#url_redirect', :as => "short_url_redirect"

end

app/models/short_url.rb
class ShortUrl < ActiveRecord::Base
	validates :longUrl, presence: true
	def self.generate_surl
		(0..9).to_a.shuffle[0,5].join
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def hello
  	render text: 'hello world'
  end
end

app/controllers/shorturls_controller.rb
class ShorturlsController < ApplicationController
	def index
		@all_urls = ShortUrl.all
	end

	def url_redirect
		lurl = $redis.get(params[:short_url])
		redirect_to lurl
	end

	def create
		@all_urls = ShortUrl.all
		@longUrl = params[:shorturl][:longUrl]
		@smallUrl = ShortUrl.generate_surl
		@surl = ShortUrl.new
		@surl.longUrl = @longUrl
		@surl.smallUrl = @smallUrl
		if @surl.save
			$redis.set(@smallUrl,@longUrl)
    		redirect_to shorturl_path(@surl)
  		else
    		render 'new'
  		end
	end

	def new
		@all_urls = ShortUrl.all
	end

	def edit
	end

	def update
	end

	def destroy
	end

	def show
		@short_url = ShortUrl.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorturls_helper.rb
module ShorturlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="../" class="navbar-brand">Turbo URL Shortner</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse">
     
    </nav>
  </div>

</head>

<body>

<div class="container">
	<div class="row">
  		<div class="col-xs-12 col-md-8">
			<%= yield %>
  		</div>
	</div>
</div>

</body>
</html>

app/views/shorturls/_created_shorturl.html.erb
<h2>Displaying URL</h2>
<p><%= @surl.longUrl %></p>
<p> >> </p>
<p> <%= short_url_redirect_url(@surl.smallUrl) %></p>

<p>[<%= link_to "<<Back", shorturls_path %>]
[<%= link_to "Create Short URL" , new_shorturl_path %> |

   [<%= link_to "Open In new Window" , short_url_redirect_url(@surl.smallUrl), :target => "_blank" %> ] | 
    <button class='my_clip_button' data-clipboard-target='fe_text' id='d_clip_button' >
    <b>Copy To Clipboard.</b> </button> ] </p>

<textarea cols='50' id='fe_text' rows='3' style="visibility: hidden;"><%= short_url_redirect_url(@surl.smallUrl) %></textarea>

 <script>
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });
</script>

app/views/shorturls/_form_error.html.erb
	<% if @surl.errors.any? %>
		    <div id="error_explanation">
		      <h2>
		        <%= pluralize(@surl.errors.count, "error") %> prohibited
		        this article from being saved:
		      </h2>
		      <ul>
		        <% @surl.errors.full_messages.each do |msg| %>
		          <li><%= msg %></li>
		        <% end %>
		      </ul>
		    </div>
		  <% end %>

app/views/shorturls/_index.html.erb
<hr></hr>
<table id="urlTable" class="table table-bordered table-striped">
<thead>
<tr>
	<th>#</th>
	<th>Long URL</th>
	<th>Short URL</th>
</tr>
</thead>

<tbody>
<% i = 0 %>
<% @all_urls.each do |s| %>
	<tr>
		<td><%= i.to_s %></td>
		<td> <%= link_to s.longUrl, s.longUrl %> </p>
		<td> <%= link_to short_url_redirect_url(s.smallUrl), short_url_redirect_url(s.smallUrl) %> </p>
		<% i = i+ 1 %>
	</tr>
<% end %>
</tbody>
</table>


<script type="text/javascript">
	$(document).ready(function() {
    $('#urlTable').DataTable();
} );
</script>

app/views/shorturls/index.html.erb
<h1>Listing all short URLs</h1>

<table id="urlTable" class="table table-bordered table-striped">
<thead>
<tr>
	<th>Long URL</th>
	<th>Short URL</th>
</tr>
</thead>

<tbody>
<% @all_urls.each do |s| %>
	<tr>
		<td> <%= s.longUrl %> </p>
		<td> <%= s.smallUrl %> </p>
	</tr>
<% end %>
</tbody>
</table>


<script type="text/javascript">
	$(document).ready(function() {
    $('#urlTable').DataTable();
} );
</script>

app/views/shorturls/new.html.erb
<%= form_for :shorturl , url: shorturls_path, html: {class: 'form-horizontal'} do |f| %>
<% if !@surl.nil? %> 
	<%= render "form_error" %>
<%end %>

	 <%= f.label "longUrl" %>
	 <p>Example http://www.google.com (Please prefix http:// or https://) </p>
	 <div class="input-group">
		<span class="input-group-addon" id="basic-addon1"></span>
		<%= f.text_field :longUrl, :class => "form-control" , "aria-describedby" =>"basic-addon1"%> 
	 </div> <!--input-group -->
	 <p>
	 <br>
	<%= f.submit 'Generate Short Url', :class => 'btn btn-success' %>
<% end %>

<%= render "index" %>

app/views/shorturls/show.html.erb
<h2>Displaying URL</h2>
<p><%= @short_url.longUrl %></p>
<p> >> </p>
<p> <%= short_url_redirect_url(@short_url.smallUrl) %></p>

<p>[<%= link_to "<<Back", "/" %>]
[<%= link_to "Create Short URL" , new_shorturl_path %> |

   [<%= link_to "Open In new Window" , short_url_redirect_url(@short_url.smallUrl), :target => "_blank" %> ] | 
    <button class='my_clip_button' data-clipboard-target='fe_text' id='d_clip_button' >
    <b>Copy To Clipboard.</b> </button> ] </p>

<textarea cols='50' id='fe_text' rows='3' style="visibility: hidden;"><%= short_url_redirect_url(@short_url.smallUrl) %></textarea>

 <script>
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });
</script>